FROM docker.io/rocker/geospatial:latest

# Install dependencies for redistricting and geojson
RUN R -e "install.packages(c('jsonlite', 'remotes', 'optparse', 'rmapshaper'), repos='http://cran.rstudio.com/')"
RUN R -e "remotes::install_github('alarm-redist/alarmdata')"
